api:
  dashboard: true
  insecure: true  # Em produção, usar autenticação

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: seu-email@example.com  # Substituir pelo seu email
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web